#!/bin/sh
# .f - aliases

# lazy fingers
alias a="awk"
alias p="pwd"
alias g="grep"
alias l="less"
alias j="jobs"
alias s="sed"

# don't alias if command doesn't exist
which colorls >> /dev/null && alias ls="colorls -lfHG" || alias ls="ls -AlhF"
alias cp="cp -r"
alias scp="scp -r"
alias mkdir="mkdir -p"
alias fdm="fdm -k"
alias poweroff="sudo shutdown -hp NOW"
alias zzz='zzz ; [[ -n $DISPLAY ]] && slock'
alias colemak="setxkbmap us -variant colemak"
