#!/bin/sh

prompt () {
	ERR=$?
	UID=$(id -u)
	JOB=$(jobs | wc -l)

	[ $UID -eq 0 ] && printf '\033[31m━' || printf '\033[30m─'
	[ $JOB -ne 0 ] && printf '\033[32m─' || printf '\033[30m─'
	[ $ERR -ne 0 ] && printf '\033[33m─' || printf '\033[30m─'
	
	printf '\033[0m'
}

PS1='$(prompt) '
