#!/bin/sh
# lazybrain can't remember tar flags for shit

NUL=/dev/null

exists () {
	which $1 &> /dev/null && return 0 || return 1
}

extract () {
	if [[ -f $1 ]]
	then
	case $1 in
	
	# extraction rules
	*.tar.gz)  exists tar        && tar xzf    $1 || tput 31  ;;
	*.tgz)     exists tar        && tar xzf    $1 || tput 31  ;;
	*.tar.xz)  exists tar        && tar xJf    $1 || tput 31  ;;
	*.tar.bz2) exists tar        && tar xjf    $1 || tput 31  ;;
	*.bz2)     exists bunzip2    && bunzip2    $1 || tput 31  ;;
	*.gz)      exists gunzip     && gunzip     $1 || tput 31  ;;
	*.xz)      exists unxz       && unxz       $1 || tput 31  ;;
	# proprietary formats below
	*.rar)     exists unrar      && unrar x    $1 || tput 31  ;;
	*.zip)     exists unzip      && unzip      $1 || tput 31  ;;
	*.Z)       exists uncompress && uncompress $1 || tput 31  ;;
	esac

	else
		echo "$1 is not a valid file"
	fi
}
