#!/bin/zsh
# lazybrain can't remember tar flags for shit

NUL=/dev/null
alias e='echo "missing command:"'

function extract () {
	if [ -f $1 ] ; then
	case $1 in
	
	# extraction rules
	*.tar.gz)  which tar     &> $NUL && tar xzf    $1 || e tar        ;;
	*.tar.xz)  which tar     &> $NUL && tar xJf    $1 || e tar        ;;
	*.tar.bz2) which tar     &> $NUL && tar xjf    $1 || e tar        ;;
	*.bz2)     which bunzip2 &> $NUL && bunzip2    $1 || e bunzip     ;;
	*.gz)      which gunzip  &> $NUL && gunzip     $1 || e gunzip     ;;
	*.tgz)     which tar     &> $NUL && tar xzf    $1 || e tar        ;;
	*.xz)      which unxz    &> $NUL && unxz       $1 || e unxz       ;;
	# proprietary formats below
#	*.rar)     which unrar   &> $NUL && unrar x    $1 || e unrar      ;;
#	*.zip)     which unzip   &> $NUL && unzip      $1 || e unzip      ;;
#	*.Z)    which uncompress &> $NUL && uncompress $1 || e uncompress ;;
	esac

	else
		echo "$1 is not a valid file"
	fi
}

unalias e

# vim: set ft=zsh :
